/**************************************************************************
*********************************  DUB.H  *********************************
***************************************************************************
*
*                              Record Level I/O
*
* Module Name: DUB.H
*
* This is the top level include file that includes all the files necessary
* for writing a DDM application.
*
* RLIO (program no. 5648-02011)
*
* Version: 1.0
* Release: 1.0
*
*
* ADSTAR Distributed Storage Manager Data Access Services:
* Version 1.0, Release 1.0, Level 0.0
* Licensed Materials - Property of IBM
* 5648-02011 (C) Copyright IBM Corporation, 1992, 1993, All Rights Reserved
* U.S. Government Users Restricted Rights - Use, duplicate or disclosure
* restricted by GSA ADP Schedule Contract with IBM Corporation.
*
***************************************************************************/

/*-------------------------------------------------------------------------
-- Code Points
--------------------------------------------------------------------------*/
#include "dubcodpt.h"

/*-------------------------------------------------------------------------
-- Common definitions
--------------------------------------------------------------------------*/
#include "dubdefs.h"

/*-------------------------------------------------------------------------
-- Function prototypes
--------------------------------------------------------------------------*/
#include "dubcalls.h"

