//
//   COMPONENT_NAME: somi
//
//   ORIGINS: 27
//
//
//   10H9767, 10H9769  (C) COPYRIGHT International Business Machines Corp. 1992,1994
//   All Rights Reserved
//   Licensed Materials - Property of IBM
//   US Government Users Restricted Rights - Use, duplication or
//   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//
//  InterfaceDef: CORBA Interface for interface definitions
//  See CORBA 7.5.4, p.134
#ifndef intfacdf_idl
#define intfacdf_idl
#include <containd.idl>
#include <containr.idl>
#include <somcls.idl>
#include <attribdf.idl>
#include <operatdf.idl>
// CORBA 7.5.4, p.134
interface InterfaceDef : Contained , Container
{
    struct FullInterfaceDescription {
	Identifier   name;
	RepositoryId id;
	RepositoryId defined_in;
	sequence<OperationDef::OperationDescription> operation;
	sequence<AttributeDef::AttributeDescription> attributes;
    };
    struct InterfaceDescription {
	Identifier   name;
	RepositoryId id;
	RepositoryId defined_in;
    };
    // The inherited describe method returns an instance of this
    // (InterfaceDescription) structure in the "value" member of the
    // Description structure defined in the Contained interface.
    // The inherited describe_contents method in the Container
    // interface returns a sequence of these Description structures
    // each carrying a reference to an InterfaceDescription structure
    // in its "value" member.
    attribute sequence<RepositoryId> base_interfaces;
    // The sequence of RepositoryIds for all of the interfaces that the
    // receiving interface inherits.  Do not free the buffer,
    // its storage is still owned by the InterfaceDef object.
    FullInterfaceDescription describe_interface();
    // Returns a description of all the operations and attributes in
    // an interface.
    attribute TypeCode instanceData;
    // [SOM-unique extension]
    //
    // The instance data members (if any) described in the SOM
    // implementation section of the IDL source file.
#ifdef __SOMIDL__
  implementation {
      releaseorder: describe_interface,
		  _get_base_interfaces, _set_base_interfaces,
		  _get_instanceData, _set_instanceData
		  ;
      callstyle = idl;
      majorversion = 2;
      minorversion = 1;
      filestem = intfacdf;
      dllname = "somir.dll";
      passthru C_h =
	""
	"    #include <somtcnst.h>"
	"    #include <somir.h>"
	"    #include <operatdf.h>"
	"    #include <attribdf.h>"
	"";
      passthru C_xh =
	""
	"    #include <somtcnst.xh>"
	"    #include <somir.xh>"
	"    #include <operatdf.xh>"
	"    #include <attribdf.xh>"
	"";
      base_interfaces: noset;
      instanceData: noset;
      somInit: override;
      somUninit: override;
      somDumpSelf: override;
      somDumpSelfInt: override;
      within: override;
      describe: override;
  };
#endif /* __SOMIDL__ */
};
#endif	/* intfacdf_idl */
