/***    VLPT.H
 *
 *
 *      MVDM Virtual Printer Exported Definitions
 ****************************************************************************
 *                                                                          *
 *                                                                          *
 *                 Copyright (c) IBM Corporation  1993                      *
 *                           All Rights Reserved                            *
 *                                                                          *
 ****************************************************************************
 *
 *      For include file hierarchy, see MVDM.H
 *
 *
 *
 */

#pragma info( none )
   #ifndef __CHKHDR__
      #pragma info( none )
   #endif
#pragma info( restore )

#ifndef __VLPT__
#define __VLPT__


/***    VLPT constants
 */


/***    VLPT data types
 */


/***    VLPT function prototypes
 */
VOID VDHENTRY VDHPrintClose(HVDM);

#endif /* __VLPT__ */

#pragma info( none )
   #ifndef __CHKHDR__
      #pragma info( restore )
   #endif
#pragma info( restore )
