//  Module Header
//
//  Module Name: WPDATAF
//
//  OS/2 Presentation Manager Workplace class definitions
//
//  Copyright (c) International Business Machines Corporation 1991, 1992
//
#ifndef wpdataf_idl
#define wpdataf_idl
#include "wpfsys.idl"
#include <somcls.idl>
interface M_WPDataFile;
interface WPDataFile : WPFileSystem
{
  ULONG wpAddFileTypePage(in HWND hwndNotebook);
  BOOL wpPrintMetaFile(in PPRINTDEST pPrintDest);
  BOOL wpPrintPifFile(in PPRINTDEST pPrintDest);
  BOOL wpPrintPrinterSpecificFile(in PPRINTDEST pPrintDest);
  BOOL wpPrintUnknownFile(in PPRINTDEST pPrintDest);
  WPObject wpQueryAssociatedProgram(in ULONG ulView,
                                    in PULONG pulHowMatched,
                                    in PSZ pszMatchString,
                                    in ULONG cbMatchString,
                                    in PSZ pszDefaultType);
  void wpSetAssociatedFileIcon();
  HPOINTER wpQueryAssociatedFileIcon();
#ifdef __SOMIDL__
  implementation {
    releaseorder: wpAddFileTypePage,wpPrintMetaFile,wpPrintPifFile,
                  wpPrintPrinterSpecificFile,wpPrintUnknownFile,wpQueryAssociatedProgram,
                  wpSetAssociatedFileIcon, wpQueryAssociatedFileIcon;
    externalstem = wpdf;
    local;
    externalprefix = df_;
    majorversion = 1;
    minorversion = 2;
    filestem = wpdataf;
    metaclass = M_WPDataFile;
    callstyle = oidl;
    dllname = "pmwp.dll";                   passthru C_h =      "        #define MAX_ASSOC_ITEMS 12";
    wpDragOver: override;
    wpRestoreState: override;
    wpSetDefaultView: override;
    wpSetRealName: override;
    wpSetType: override;
    wpAddSettingsPages: override;
    wpAddObjectWindowPage: override;
    wpOpen: override;
    wpPrintObject: override;
    wpModifyPopupMenu: override;
    wpMenuItemSelected: override;
    wpMenuItemHelpSelected: override;
    wpQueryDefaultHelp: override;
    wpFormatDragItem: override;
    wpConfirmRenameFileWithExt: override;
    wpQueryIcon: override;
    somDefaultInit: override;              somDestruct: override;               };
#endif /* __SOMIDL__ */
};
interface M_WPDataFile : M_WPFileSystem
{
#ifdef __SOMIDL__
  implementation {
    externalstem = wpdf;
    local;
    externalprefix = dfM_;
    majorversion = 1;
    minorversion = 2;
    filestem = wpdataf;
    callstyle = oidl;
    dllname = "pmwp.dll";                   wpclsQueryTitle: override;
    wpclsQueryIconData: override;
    wpclsQueryStyle: override;
    wpclsQueryDefaultView: override;
    wpclsQueryDefaultHelp: override;
  };
#endif /* __SOMIDL__ */
};
#endif  /* wpdataf_idl */
