//  Module Header
//
//  Module Name: WPPORT
//
//  OS/2 Presentation Manager Workplace class definitions
//
//  Copyright (c) International Business Machines Corporation 1991, 1992
//
#ifndef wpport_idl
#define wpport_idl
#include "wptrans.idl"
#include <somcls.idl>
#include <wprttype.idl>
interface M_WPPort;
interface WPPort : WPTransient
{
#ifdef __SOMIDL__
  implementation {
    releaseorder: prtGetPortInfo,prtSetPortInfo,prtSettings,prtGetDeviceObject,
                  prtSetPortDiscardhwndDlg,prtSetPortInstallhwndDlg,
                  prtPrintPort,prtSetIcon,prtChangePort;
    externalstem = WPport;
    local;
    externalprefix = port_;
    majorversion = 1;
    minorversion = 1;
    filestem = wpport;
    metaclass = M_WPPort;
    callstyle = oidl;
    passthru C_ih =     "#define JO_VERSION_MAJOR  1"
"#define JO_VERSION_MINOR  1"
""
"    /* port multi selected flags */"
"#define PORT_FLAG_MUTISELPORT    0x00000001L"
"#define SIZE_PORT_NAME           257"
"";
    passthru C_h =     ""
"/* common context menu ids */"
"#define WPPOIDM_PORT_REDIRECT       7100"
"#define WPPOIDM_PORT_INSTALL        8001"
"";
    wpInitData: override;
    wpUnInitData: override;
    somDumpSelfInt: override;
    wpQueryTitle: override;
    wpQueryIcon: override;
    wpFilterPopupMenu: override;
    wpFree: override;
    wpModifyPopupMenu: override;
    wpMenuItemSelected: override;
    wpMenuItemHelpSelected: override;
    wpOpen: override;
    wpDrop: override;
    wpDragOver: override;
    wpCnrSetEmphasis: override;
  };
#endif /* __SOMIDL__ */
};
interface M_WPPort
{
#ifdef __SOMIDL__
  implementation {
    externalstem = WPport;
    local;
    externalprefix = portM_;
    functionprefix = portM_;
    majorversion = 1;
    minorversion = 1;
    filestem = wpport;
    callstyle = oidl;
    wpclsQueryTitle: override;
    wpclsQueryIcon: override;
    wpclsQueryIconData: override;
    wpclsQueryDefaultHelp: override;
    wpclsQueryDefaultView: override;
    wpclsQueryStyle: override;
  };
#endif /* __SOMIDL__ */
};
#endif  /* wpport_idl */
