//  Module Header
//
//  Module Name: WPPOWER
//
//  OS/2 Presentation Manager Workplace class definitions
//
//  Copyright (c) International Business Machines Corporation 1991, 1992
//
#ifndef wppower_idl
#define wppower_idl
#include "wpabs.idl"
#include <somcls.idl>
interface M_WPPower;
interface WPPower : WPAbstract
{
  ULONG wpAddPowerPage(in HWND hwndNotebook);
  ULONG wpAddPowerViewPage(in HWND hwndNotebook);
  BOOL wpChangePowerState(in ULONG ulParm1,
                          in ULONG ulParm2);
  BOOL wpQueryAutoRefresh();
  ULONG wpQueryDefStatusView();
  BOOL wpQueryPowerConfirmation();
  BOOL wpQueryPowerManagement();
  ULONG wpQueryRefreshRate();
  void wpSetAutoRefresh(in BOOL fAutoRefresh);
  void wpSetDefStatusView(in ULONG ulDefStatus);
  void wpSetPowerConfirmation(in BOOL fConfirm);
  BOOL wpSetPowerManagement(in BOOL fPower);
  BOOL wpSetRefreshRate(in ULONG ulRefreshRate);
#ifdef __SOMIDL__
  implementation {
    releaseorder: wpChangePowerState,wpSetPowerManagement,wpQueryPowerManagement,
                  wpSetPowerConfirmation,wpQueryPowerConfirmation,
                  wpAddPowerPage,wpAddPowerViewPage,wpSetAutoRefresh,
                  wpQueryAutoRefresh,wpQueryRefreshRate,wpSetRefreshRate,
                  wpQueryEventSemaphore,wpSetEventSemaphore,wpQueryDefStatusView,
                  wpSetDefStatusView;
    externalstem = WPPower;
    local;
    externalprefix = pwr_;
    majorversion = 1;
    minorversion = 2;
    filestem = wppower;
    metaclass = M_WPPower;
    callstyle = oidl;
    dllname = "wpconfig.dll";
    passthru C_h =      "    #define OPEN_STATUS  131"
"    #define OPEN_BATTERY 132";
    wpOpen: override;
    wpFilterPopupMenu: override;
    wpAddSettingsPages: override;
    wpModifyPopupMenu: override;
    wpMenuItemSelected: override;
    wpInitData: override;
    wpSaveState: override;
    wpRestoreState: override;
    wpMenuItemHelpSelected: override;
    wpAddObjectWindowPage: override;
    somDefaultInit: override;                 somDestruct:    override;               };
#endif /* __SOMIDL__ */
};
interface M_WPPower : M_WPAbstract
{
#ifdef __SOMIDL__
  implementation {
    externalstem = WPPower;
    local;
    externalprefix = pwrM_;
    majorversion = 1;
    minorversion = 2;
    filestem = wppower;
    callstyle = oidl;
    dllname = "wpconfig.dll";
    wpclsQueryDefaultView: override;
    wpclsQueryDefaultHelp: override;
    wpclsQueryIconData: override;
    wpclsQueryStyle: override;
    wpclsQueryTitle: override;
  };
#endif /* __SOMIDL__ */
};
#endif  /* wppower_idl */
