/*************************************************************************
 * File Name    :  MOVIE.H
 *
 * Description  :  This file contains the definitions used by the Movie
 *                 Sample Application program.
 *
 * Copyright (C) IBM 1993
 *************************************************************************/

#define INIT_VOLUME                100          /* initial volume level  */

#define ID_MESSAGEBOX              1
#define ID_ICON                    100

#define IDD_MAIN_WINDOW            100
#define IDC_GPB_STOP               101
#define IDC_GPB_PLAY               102
#define IDC_GPB_PAUSE              103
#define IDC_GPB_REWIND             104
#define IDC_VOLUME_SLIDER          105
#define IDC_GPB_EDIT               106
#define IDC_RADIO1                 109
#define IDC_RADIO2                 110
#define ID_APPWINDOW               111

#define IDM_HELP_INDEX             131
#define IDM_HELP_GENERAL           132
#define IDM_HELP_USING             133
#define IDM_HELP_KEYS              134

/*
 * Button bitmap id's
 */

#define ID_BMP_PLAY0               201
#define ID_BMP_PAUSE               206
#define ID_BMP_STOP                207
#define ID_BMP_REWIND              208

#define ID_MOVIE_HELPTABLE         300
#define ID_SUBTABLE_MESSAGEBOX     301

/*
 * String defines for the string table.
 */
#define LEN_ERROR_TITLE                     60
#define LEN_ERROR_MESSAGE                   128
#define LEN_PROGRAM_TITLE                   60
#define LEN_HELP_WINDOW_TITLE               60
#define LEN_HELP_LIBRARY_NAME               13 /* DOS limit   */

#define IDS_PROGRAM_TITLE                   1
#define IDS_MOVIE_ERROR                     2
#define IDS_HELP_WINDOW_TITLE               3
#define IDS_HELP_LIBRARY_NAME               4
#define IDS_DEFAULTSIZE                     5
#define IDS_HELP_CREATION_FAILED            6
#define IDS_UNKNOWN                         7
#define IDS_CANNOT_FIND_MOVIE_FILE          8
#define IDS_EDIT_MOVIE                      9
#define IDS_CANNOT_LOAD_MOVIE_FILE          10
#define IDS_HELP                            11

