name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: JCL
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks For Your Concern"
        pr-message: "Thank you for contributing to the COBOL Archive!"
